version: '3.5'
services:
  api1: # API - Instância 01
    build: .
    # depends_on:
    #   - db
    environment:
      PORT: 3001 
    ports:
      - "3001:3001"
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.25'
    #       memory: '0.5GB'

  # nginx: # Load Balancer
  #   image: nginx:latest
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - api1
  #   ports:
  #     - "9999:9999"
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.2'
  #         memory: '0.5GB'

  # db: # Banco de dados
  #  image: postgres
  #  environment:
  #     POSTGRES_USER: postgres 
  #     POSTGRES_PASSWORD: postgres
  #  deploy:
  #     resources:
  #       limits:
  #         cpus: '0.75'
  #         memory: '1.5GB'


