-- Create table people
CREATE TABLE IF NOT EXISTS PESSOAS (
    ID UUID PRIMARY KEY,
    APELIDO VARCHAR(32) UNIQUE NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    NASCIMENTO DATE NOT NULL,
    STACK VARCHAR(1024),
    SEARCH VARCHAR(1160) GENERATED ALWAYS AS (
        LOWER(NOME || ' ' || APELIDO || ' ' || COALESCE(STACK, ''))
    ) STORED NOT NULL
);

-- Create extensions
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- Create search index
CREATE INDEX CONCURRENTLY IF NOT EXISTS PESSOAS_SEARCH_IDX ON PESSOAS USING GIST (SEARCH GIST_TRGM_OPS(SIGLEN=64));
